name: Deploy Hugo site to thoni-miguel.github.io

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy to thoni-miguel.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: thoni-miguel/thoni-miguel.github.io
          publish_branch: main
          publish_dir: ./public
          user_name: thoni-miguel
          user_email: thonimigueldev@gmail.com
